/**
 * Dicecup School Management API
 *
 * Contact: support@dicecup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AssessmentAnswerDto } from './assessment-answer-dto';

export interface AssessmentSubmissionRequest {
  answers?: Array<AssessmentAnswerDto>;
}
