/**
 * Dicecup School Management API
 *
 * Contact: support@dicecup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClassTerm } from './class-term';


export interface Class { 
    id?: string;
    name?: string;
    terms?: Array<ClassTerm>;
}

