/**
 * Dicecup School Management API
 *
 * Contact: support@dicecup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {Class} from './class';
import {Term} from './term';


export interface ClassTerm {
    id?: string;
    schoolClass: Class;
    term: Term;
    status: ClassTermStatusEnum;
    createdAt: string;
    updatedAt: string;
}

export enum ClassTermStatusEnum {
    Active = 'ACTIVE',
    Inactive = 'INACTIVE'
};



