/**
 * Dicecup School Management API
 *
 * Contact: support@dicecup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface InviteRedeemResponseDto {
  userId?: string;
  jwt?: string;
  email?: string;
  role?: InviteRedeemResponseDtoRoleEnum;
}
export enum InviteRedeemResponseDtoRoleEnum {
  Admin = 'ADMIN',
  Teacher = 'TEACHER',
  Student = 'STUDENT',
}
