/**
 * Dicecup School Management API
 *
 * Contact: support@dicecup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ProjectDto {
  id?: string;
  name?: string;
  description?: string;
  active?: boolean;
  classId?: string;
  termId?: string;
}
