/**
 * Dicecup School Management API
 *
 * Contact: support@dicecup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StudentAssessmentDetailDTO } from './student-assessment-detail-dto';

export interface ProjectAssessmentOverviewDTO {
  projectId?: string;
  students?: Array<StudentAssessmentDetailDTO>;
}
