/**
 * Dicecup School Management API
 *
 * Contact: support@dicecup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Student } from './student';
import { ProjectGroup } from './project-group';

export interface ProjectGroupMember {
  id?: string;
  projectGroup: ProjectGroup;
  student: Student;
  role?: ProjectGroupMemberRoleEnum;
  createdAt: string;
  updatedAt: string;
}

export enum ProjectGroupMemberRoleEnum {
  Leader = 'LEADER',
  Member = 'MEMBER',
}
