/**
 * Dicecup School Management API
 *
 * Contact: support@dicecup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Project } from './project';
import { ProjectGroupMember } from './project-group-member';
import { Teacher } from './teacher';

export interface ProjectGroup {
  id?: string;
  project: Project;
  groupNumber: number;
  supervisingTeacher?: Teacher;
  createdAt: string;
  updatedAt: string;
  members?: Array<ProjectGroupMember>;
}
