/**
 * Dicecup School Management API
 *
 * Contact: support@dicecup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProjectGroupMemberDto {
    id?: string;
    groupId?: string;
    studentId?: string;
    role?: ProjectGroupMemberDtoRoleEnum;
}

export enum ProjectGroupMemberDtoRoleEnum {
    Leader = 'LEADER',
    Member = 'MEMBER'
};



