/**
 * Dicecup School Management API
 *
 * Contact: support@dicecup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Class } from './class';
import { ProjectGroup } from './project-group';

export interface Project {
  id?: string;
  name: string;
  description?: string;
  schoolClass: Class;
  term: any | null;
  createdAt: string;
  updatedAt: string;
  active: boolean;
  projectGroups?: Array<ProjectGroup>;
}
