/**
 * Dicecup School Management API
 *
 * Contact: support@dicecup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QuestionDto } from './question-dto';

export interface QuestionnaireDto {
  id?: string;
  projectId?: string;
  status?: QuestionnaireDtoStatusEnum;
  questions?: Array<QuestionDto>;
}

export enum QuestionnaireDtoStatusEnum {
  Draft = 'DRAFT',
  Open = 'OPEN',
  Closed = 'CLOSED',
}
