/**
 * Dicecup School Management API
 *
 * Contact: support@dicecup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SchoolYearDto { 
    id?: string;
    name?: string;
    startDate?: string;
    endDate?: string;
    status?: SchoolYearDtoStatusEnum;
}
export enum SchoolYearDtoStatusEnum {
    Active = 'ACTIVE',
    Closed = 'CLOSED'
};



