/**
 * Dicecup School Management API
 *
 * Contact: support@dicecup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {Term} from './term';


export interface SchoolYear {
    id?: string;
    name: string;
    startDate: string;
    endDate: string;
    status: SchoolYearStatusEnum;
    createdAt: string;
    updatedAt: string;
    terms?: Array<Term>;
}

export enum SchoolYearStatusEnum {
    Active = 'ACTIVE',
    Closed = 'CLOSED'
};



