/**
 * Dicecup School Management API
 *
 * Contact: support@dicecup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {User} from './user';
import {Class} from './class';


export interface Student {
    id?: string;
    user?: User;
    clazz?: Class;
}

