/**
 * Dicecup School Management API
 *
 * Contact: support@dicecup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StudentInClassDto {
    studentId?: string;
    firstName?: string;
    lastName?: string;
    classId?: string;
    className?: string;
}

