/**
 * Dicecup School Management API
 *
 * Contact: support@dicecup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {SubjectScoreDto} from './subject-score-dto';


export interface StudentSubjectAssessmentDto {
    studentId?: string;
    studentName?: string;
    projectGroupId?: string;
    projectName?: string;
    questionnaireId?: string;
    subjects?: Array<SubjectScoreDto>;
}

