/**
 * Dicecup School Management API
 *
 * Contact: support@dicecup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StudentQuestionAssessmentDTO } from './student-question-assessment-dto';

export interface StudentAssessmentDetailDTO {
  studentId?: string;
  studentName?: string;
  selfAvg?: number;
  peerAvg?: number;
  combinedAvg?: number;
  teacherGrade?: number;
  delta?: number;
  tendencyLabel?: StudentAssessmentDetailDTOTendencyLabelEnum;
  questions?: Array<StudentQuestionAssessmentDTO>;
}

export enum StudentAssessmentDetailDTOTendencyLabelEnum {
  Overestimates = 'OVERESTIMATES',
  Underestimates = 'UNDERESTIMATES',
  Aligned = 'ALIGNED',
}
