/**
 * Dicecup School Management API
 *
 * Contact: support@dicecup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SubjectScoreDto {
    questionId?: string;
    position?: number;
    key?: string;
    label?: string;
    teacherScore?: number;
    selfScore?: number;
    peerScoreAverage?: number;
    peerScoreCount?: number;
    tendency?: SubjectScoreDtoTendencyEnum;
}

export enum SubjectScoreDtoTendencyEnum {
    Aligned = 'ALIGNED',
    SelfHigherThanPeer = 'SELF_HIGHER_THAN_PEER',
    SelfLowerThanPeer = 'SELF_LOWER_THAN_PEER',
    PeerHigherThanTeacher = 'PEER_HIGHER_THAN_TEACHER',
    PeerLowerThanTeacher = 'PEER_LOWER_THAN_TEACHER'
};



