/**
 * Dicecup School Management API
 *
 * Contact: support@dicecup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {TeacherTermContextDto} from './teacher-term-context-dto';


export interface TeacherClassContextDto {
    classId?: string;
    className?: string;
    terms?: Array<TeacherTermContextDto>;
}

