/**
 * Dicecup School Management API
 *
 * Contact: support@dicecup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface TeacherProjectGroupContextDto {
  projectGroupId?: string;
  projectName?: string;
  studentCount?: number;
}
