/**
 * Dicecup School Management API
 *
 * Contact: support@dicecup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TeacherProjectGroupContextDto } from './teacher-project-group-context-dto';


export interface TeacherTermContextDto { 
    termId?: string;
    termName?: string;
    isCurrent?: boolean;
    projectGroups?: Array<TeacherProjectGroupContextDto>;
}

