/**
 * Dicecup School Management API
 *
 * Contact: support@dicecup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TeacherClassContextDto } from './teacher-class-context-dto';

export interface TeacherContextDto {
  teacherId?: string;
  classes?: Array<TeacherClassContextDto>;
}
