/**
 * Dicecup School Management API
 *
 * Contact: support@dicecup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {Project} from './project';
import {ClassTerm} from './class-term';
import {SchoolYear} from './school-year';


export interface Term {
    id?: string;
    name: string;
    status: TermStatusEnum;
    sequenceNumber?: number;
    schoolYear: SchoolYear;
    startDate: string;
    endDate: string;
    createdAt: string;
    updatedAt: string;
    classTerms?: Array<ClassTerm>;
    projects?: Array<Project>;
}

export enum TermStatusEnum {
    Open = 'OPEN',
    Closed = 'CLOSED'
};



