/**
 * Dicecup School Management API
 *
 * Contact: support@dicecup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TermDto {
    id?: string;
    name?: string;
    sequenceNumber?: number;
    startDate?: string;
    endDate?: string;
    status?: TermDtoStatusEnum;
    schoolYearId?: string;
}

export enum TermDtoStatusEnum {
    Open = 'OPEN',
    Closed = 'CLOSED'
};



