/**
 * Dicecup School Management API
 *
 * Contact: support@dicecup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {GrantedAuthority} from './granted-authority';
import {Teacher} from './teacher';
import {UserInfo} from './user-info';
import {Admin} from './admin';
import {Student} from './student';


export interface User {
    createdAt?: string;
    updatedAt?: string;
    createdBy?: string;
    updatedBy?: string;
    id?: string;
    username: string;
    passwordHash: string;
    enabled?: boolean;
    disabledAt?: string;
    userInfo?: UserInfo;
    admin?: Admin;
    student?: Student;
    teacher?: Teacher;
    password?: string;
    authorities?: Array<GrantedAuthority>;
    accountNonExpired?: boolean;
    accountNonLocked?: boolean;
    accountUsername?: string;
    credentialsNonExpired?: boolean;
}

