/**
 * Dicecup School Management API
 *
 * Contact: support@dicecup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserInfoDto } from './user-info-dto';


export interface UserDto { 
    id?: string;
    username?: string;
    enabled?: boolean;
    userInfo?: UserInfoDto;
    role?: UserDtoRoleEnum;
}
export enum UserDtoRoleEnum {
    Admin = 'ADMIN',
    Teacher = 'TEACHER',
    Student = 'STUDENT'
};



