/**
 * Dicecup School Management API
 *
 * Contact: support@dicecup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import {Inject, Injectable, Optional} from '@angular/core';
import {
    HttpClient, HttpHeaders, HttpParams,
    HttpResponse, HttpEvent, HttpParameterCodec, HttpContext
} from '@angular/common/http';
import {CustomHttpParameterCodec} from '../encoder';
import {Observable} from 'rxjs';

// @ts-ignore
import {CreateInviteRequestDto} from '../model/create-invite-request-dto';
// @ts-ignore
import {InviteCreatedResponseDto} from '../model/invite-created-response-dto';
// @ts-ignore
import {InviteRedeemRequestDto} from '../model/invite-redeem-request-dto';
// @ts-ignore
import {InviteRedeemResponseDto} from '../model/invite-redeem-response-dto';
// @ts-ignore
import {InviteValidationRequestDto} from '../model/invite-validation-request-dto';
// @ts-ignore
import {InviteValidationResponseDto} from '../model/invite-validation-response-dto';

// @ts-ignore
import {BASE_PATH, COLLECTION_FORMATS} from '../variables';
import {Configuration} from '../configuration';
import {BaseService} from '../api.base.service';


@Injectable({
    providedIn: 'root'
})
export class InvitationControllerService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string | string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * @param createInviteRequestDto
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public create(createInviteRequestDto: CreateInviteRequestDto, observe?: 'body', reportProgress?: boolean, options?: {
        httpHeaderAccept?: '*/*',
        context?: HttpContext,
        transferCache?: boolean
    }): Observable<InviteCreatedResponseDto>;
    public create(createInviteRequestDto: CreateInviteRequestDto, observe?: 'response', reportProgress?: boolean, options?: {
        httpHeaderAccept?: '*/*',
        context?: HttpContext,
        transferCache?: boolean
    }): Observable<HttpResponse<InviteCreatedResponseDto>>;
    public create(createInviteRequestDto: CreateInviteRequestDto, observe?: 'events', reportProgress?: boolean, options?: {
        httpHeaderAccept?: '*/*',
        context?: HttpContext,
        transferCache?: boolean
    }): Observable<HttpEvent<InviteCreatedResponseDto>>;
    public create(createInviteRequestDto: CreateInviteRequestDto, observe: any = 'body', reportProgress: boolean = false, options?: {
        httpHeaderAccept?: '*/*',
        context?: HttpContext,
        transferCache?: boolean
    }): Observable<any> {
        if (createInviteRequestDto === null || createInviteRequestDto === undefined) {
            throw new Error('Required parameter createInviteRequestDto was null or undefined when calling create.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/invites/create`;
        const {basePath, withCredentials} = this.configuration;
        return this.httpClient.request<InviteCreatedResponseDto>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: createInviteRequestDto,
                responseType: <any>responseType_,
                ...(withCredentials ? {withCredentials} : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param inviteRedeemRequestDto
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public redeem(inviteRedeemRequestDto: InviteRedeemRequestDto, observe?: 'body', reportProgress?: boolean, options?: {
        httpHeaderAccept?: '*/*',
        context?: HttpContext,
        transferCache?: boolean
    }): Observable<InviteRedeemResponseDto>;
    public redeem(inviteRedeemRequestDto: InviteRedeemRequestDto, observe?: 'response', reportProgress?: boolean, options?: {
        httpHeaderAccept?: '*/*',
        context?: HttpContext,
        transferCache?: boolean
    }): Observable<HttpResponse<InviteRedeemResponseDto>>;
    public redeem(inviteRedeemRequestDto: InviteRedeemRequestDto, observe?: 'events', reportProgress?: boolean, options?: {
        httpHeaderAccept?: '*/*',
        context?: HttpContext,
        transferCache?: boolean
    }): Observable<HttpEvent<InviteRedeemResponseDto>>;
    public redeem(inviteRedeemRequestDto: InviteRedeemRequestDto, observe: any = 'body', reportProgress: boolean = false, options?: {
        httpHeaderAccept?: '*/*',
        context?: HttpContext,
        transferCache?: boolean
    }): Observable<any> {
        if (inviteRedeemRequestDto === null || inviteRedeemRequestDto === undefined) {
            throw new Error('Required parameter inviteRedeemRequestDto was null or undefined when calling redeem.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/invites/redeem`;
        const {basePath, withCredentials} = this.configuration;
        return this.httpClient.request<InviteRedeemResponseDto>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: inviteRedeemRequestDto,
                responseType: <any>responseType_,
                ...(withCredentials ? {withCredentials} : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param inviteValidationRequestDto
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public validate(inviteValidationRequestDto: InviteValidationRequestDto, observe?: 'body', reportProgress?: boolean, options?: {
        httpHeaderAccept?: '*/*',
        context?: HttpContext,
        transferCache?: boolean
    }): Observable<InviteValidationResponseDto>;
    public validate(inviteValidationRequestDto: InviteValidationRequestDto, observe?: 'response', reportProgress?: boolean, options?: {
        httpHeaderAccept?: '*/*',
        context?: HttpContext,
        transferCache?: boolean
    }): Observable<HttpResponse<InviteValidationResponseDto>>;
    public validate(inviteValidationRequestDto: InviteValidationRequestDto, observe?: 'events', reportProgress?: boolean, options?: {
        httpHeaderAccept?: '*/*',
        context?: HttpContext,
        transferCache?: boolean
    }): Observable<HttpEvent<InviteValidationResponseDto>>;
    public validate(inviteValidationRequestDto: InviteValidationRequestDto, observe: any = 'body', reportProgress: boolean = false, options?: {
        httpHeaderAccept?: '*/*',
        context?: HttpContext,
        transferCache?: boolean
    }): Observable<any> {
        if (inviteValidationRequestDto === null || inviteValidationRequestDto === undefined) {
            throw new Error('Required parameter inviteValidationRequestDto was null or undefined when calling validate.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/invites/validate`;
        const {basePath, withCredentials} = this.configuration;
        return this.httpClient.request<InviteValidationResponseDto>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: inviteValidationRequestDto,
                responseType: <any>responseType_,
                ...(withCredentials ? {withCredentials} : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

}
