/**
 * Dicecup School Management API
 *
 * Contact: support@dicecup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import {Inject, Injectable, Optional} from '@angular/core';
import {
    HttpClient, HttpHeaders, HttpParams,
    HttpResponse, HttpEvent, HttpParameterCodec, HttpContext
} from '@angular/common/http';
import {CustomHttpParameterCodec} from '../encoder';
import {Observable} from 'rxjs';

// @ts-ignore
import {PasswordResetCommitRequestDto} from '../model/password-reset-commit-request-dto';
// @ts-ignore
import {PasswordResetCreateRequestDto} from '../model/password-reset-create-request-dto';
// @ts-ignore
import {PasswordResetCreateResponseDto} from '../model/password-reset-create-response-dto';
// @ts-ignore
import {PasswordResetValidateRequestDto} from '../model/password-reset-validate-request-dto';
// @ts-ignore
import {PasswordResetValidateResponseDto} from '../model/password-reset-validate-response-dto';

// @ts-ignore
import {BASE_PATH, COLLECTION_FORMATS} from '../variables';
import {Configuration} from '../configuration';
import {BaseService} from '../api.base.service';


@Injectable({
    providedIn: 'root'
})
export class PasswordResetControllerService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string | string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * @param passwordResetCommitRequestDto
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public commit(passwordResetCommitRequestDto: PasswordResetCommitRequestDto, observe?: 'body', reportProgress?: boolean, options?: {
        httpHeaderAccept?: undefined,
        context?: HttpContext,
        transferCache?: boolean
    }): Observable<any>;
    public commit(passwordResetCommitRequestDto: PasswordResetCommitRequestDto, observe?: 'response', reportProgress?: boolean, options?: {
        httpHeaderAccept?: undefined,
        context?: HttpContext,
        transferCache?: boolean
    }): Observable<HttpResponse<any>>;
    public commit(passwordResetCommitRequestDto: PasswordResetCommitRequestDto, observe?: 'events', reportProgress?: boolean, options?: {
        httpHeaderAccept?: undefined,
        context?: HttpContext,
        transferCache?: boolean
    }): Observable<HttpEvent<any>>;
    public commit(passwordResetCommitRequestDto: PasswordResetCommitRequestDto, observe: any = 'body', reportProgress: boolean = false, options?: {
        httpHeaderAccept?: undefined,
        context?: HttpContext,
        transferCache?: boolean
    }): Observable<any> {
        if (passwordResetCommitRequestDto === null || passwordResetCommitRequestDto === undefined) {
            throw new Error('Required parameter passwordResetCommitRequestDto was null or undefined when calling commit.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/auth/password-reset/commit`;
        const {basePath, withCredentials} = this.configuration;
        return this.httpClient.request<any>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: passwordResetCommitRequestDto,
                responseType: <any>responseType_,
                ...(withCredentials ? {withCredentials} : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param passwordResetCreateRequestDto
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public create1(passwordResetCreateRequestDto: PasswordResetCreateRequestDto, observe?: 'body', reportProgress?: boolean, options?: {
        httpHeaderAccept?: '*/*',
        context?: HttpContext,
        transferCache?: boolean
    }): Observable<PasswordResetCreateResponseDto>;
    public create1(passwordResetCreateRequestDto: PasswordResetCreateRequestDto, observe?: 'response', reportProgress?: boolean, options?: {
        httpHeaderAccept?: '*/*',
        context?: HttpContext,
        transferCache?: boolean
    }): Observable<HttpResponse<PasswordResetCreateResponseDto>>;
    public create1(passwordResetCreateRequestDto: PasswordResetCreateRequestDto, observe?: 'events', reportProgress?: boolean, options?: {
        httpHeaderAccept?: '*/*',
        context?: HttpContext,
        transferCache?: boolean
    }): Observable<HttpEvent<PasswordResetCreateResponseDto>>;
    public create1(passwordResetCreateRequestDto: PasswordResetCreateRequestDto, observe: any = 'body', reportProgress: boolean = false, options?: {
        httpHeaderAccept?: '*/*',
        context?: HttpContext,
        transferCache?: boolean
    }): Observable<any> {
        if (passwordResetCreateRequestDto === null || passwordResetCreateRequestDto === undefined) {
            throw new Error('Required parameter passwordResetCreateRequestDto was null or undefined when calling create1.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/auth/password-reset/create`;
        const {basePath, withCredentials} = this.configuration;
        return this.httpClient.request<PasswordResetCreateResponseDto>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: passwordResetCreateRequestDto,
                responseType: <any>responseType_,
                ...(withCredentials ? {withCredentials} : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param id
     * @param format
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public qrCode(id: string, format?: string, observe?: 'body', reportProgress?: boolean, options?: {
        httpHeaderAccept?: '*/*',
        context?: HttpContext,
        transferCache?: boolean
    }): Observable<string>;
    public qrCode(id: string, format?: string, observe?: 'response', reportProgress?: boolean, options?: {
        httpHeaderAccept?: '*/*',
        context?: HttpContext,
        transferCache?: boolean
    }): Observable<HttpResponse<string>>;
    public qrCode(id: string, format?: string, observe?: 'events', reportProgress?: boolean, options?: {
        httpHeaderAccept?: '*/*',
        context?: HttpContext,
        transferCache?: boolean
    }): Observable<HttpEvent<string>>;
    public qrCode(id: string, format?: string, observe: any = 'body', reportProgress: boolean = false, options?: {
        httpHeaderAccept?: '*/*',
        context?: HttpContext,
        transferCache?: boolean
    }): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling qrCode.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>format, 'format');

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/auth/password-reset/${this.configuration.encodeParam({
            name: "id",
            value: id,
            in: "path",
            style: "simple",
            explode: false,
            dataType: "string",
            dataFormat: "uuid"
        })}/qrcode`;
        const {basePath, withCredentials} = this.configuration;
        return this.httpClient.request<string>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? {withCredentials} : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param passwordResetValidateRequestDto
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public validate1(passwordResetValidateRequestDto: PasswordResetValidateRequestDto, observe?: 'body', reportProgress?: boolean, options?: {
        httpHeaderAccept?: '*/*',
        context?: HttpContext,
        transferCache?: boolean
    }): Observable<PasswordResetValidateResponseDto>;
    public validate1(passwordResetValidateRequestDto: PasswordResetValidateRequestDto, observe?: 'response', reportProgress?: boolean, options?: {
        httpHeaderAccept?: '*/*',
        context?: HttpContext,
        transferCache?: boolean
    }): Observable<HttpResponse<PasswordResetValidateResponseDto>>;
    public validate1(passwordResetValidateRequestDto: PasswordResetValidateRequestDto, observe?: 'events', reportProgress?: boolean, options?: {
        httpHeaderAccept?: '*/*',
        context?: HttpContext,
        transferCache?: boolean
    }): Observable<HttpEvent<PasswordResetValidateResponseDto>>;
    public validate1(passwordResetValidateRequestDto: PasswordResetValidateRequestDto, observe: any = 'body', reportProgress: boolean = false, options?: {
        httpHeaderAccept?: '*/*',
        context?: HttpContext,
        transferCache?: boolean
    }): Observable<any> {
        if (passwordResetValidateRequestDto === null || passwordResetValidateRequestDto === undefined) {
            throw new Error('Required parameter passwordResetValidateRequestDto was null or undefined when calling validate1.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/auth/password-reset/validate`;
        const {basePath, withCredentials} = this.configuration;
        return this.httpClient.request<PasswordResetValidateResponseDto>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: passwordResetValidateRequestDto,
                responseType: <any>responseType_,
                ...(withCredentials ? {withCredentials} : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

}
