CREATE EXTENSION IF NOT EXISTS citext;
CREATE SEQUENCE IF NOT EXISTS project_subject_seq START WITH 1 INCREMENT BY 50;


CREATE TABLE admin
(
    user_id UUID NOT NULL,
    CONSTRAINT pk_admin PRIMARY KEY (user_id)
);

CREATE TABLE assessment_question
(
    id UUID NOT NULL,
    CONSTRAINT pk_assessmentquestion PRIMARY KEY (id)
);

CREATE TABLE audit_logs
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    actor_id UUID,
    action    VARCHAR(255)                            NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    details  VARCHAR(255),
    resource VARCHAR(255) NOT NULL,
    CONSTRAINT pk_audit_logs PRIMARY KEY (id)
);

CREATE TABLE school_class
(
    id   UUID         NOT NULL,
    name VARCHAR(100) NOT NULL,
    CONSTRAINT pk_class PRIMARY KEY (id)
);

CREATE TABLE class_projects
(
    id         UUID    NOT NULL,
    school_class_id   UUID    NOT NULL,
    project_id UUID    NOT NULL,
    active     BOOLEAN NOT NULL,
    valid_from TIMESTAMP WITHOUT TIME ZONE,
    valid_to   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_class_projects PRIMARY KEY (id)
);

CREATE TABLE grades
(
    id                 UUID                        NOT NULL,
    project_subject_id BIGINT                      NOT NULL,
    student_id         UUID                        NOT NULL,
    teacher_id         UUID                        NOT NULL,
    grade_value        DOUBLE PRECISION            NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_grades PRIMARY KEY (id)
);

CREATE TABLE group_members
(
    id         UUID NOT NULL,
    student_id UUID NOT NULL,
    group_id   UUID NOT NULL,
    CONSTRAINT pk_group_members PRIMARY KEY (id)
);

CREATE TABLE password_reset
(
    id           UUID                        NOT NULL,
    user_id      UUID                        NOT NULL,
    token_hash   BYTEA                       NOT NULL,
    token_salt   BYTEA                       NOT NULL,
    status       VARCHAR(255)                NOT NULL,
    expires_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    used_at      TIMESTAMP WITHOUT TIME ZONE,
    note         VARCHAR(255),
    public_token VARCHAR(255),
    CONSTRAINT pk_password_reset PRIMARY KEY (id)
);

CREATE TABLE project
(
    id          UUID                        NOT NULL,
    school_class_id    UUID,
    name        VARCHAR(200),
    description VARCHAR(255),
    created_by  UUID,
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    active      BOOLEAN                     NOT NULL,
    CONSTRAINT pk_project PRIMARY KEY (id)
);

CREATE TABLE project_subject
(
    id         BIGINT        NOT NULL,
    project_id UUID          NOT NULL,
    subject_id UUID          NOT NULL,
    weight     DECIMAL(5, 2) NOT NULL,
    CONSTRAINT pk_project_subject PRIMARY KEY (id)
);

CREATE TABLE registration_invites
(
    id           UUID                        NOT NULL,
    email        CITEXT                      NOT NULL,
    role         VARCHAR(255)                NOT NULL,
    school_class_id     UUID,
    public_token VARCHAR(255),
    token_hash   BYTEA                       NOT NULL,
    token_salt   BYTEA                       NOT NULL,
    status       VARCHAR(255)                NOT NULL,
    expires_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    uses_count   INTEGER                     NOT NULL,
    max_uses     INTEGER                     NOT NULL,
    created_by   UUID                        NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    used_at      TIMESTAMP WITHOUT TIME ZONE,
    note         VARCHAR(255),
    CONSTRAINT pk_registration_invites PRIMARY KEY (id)
);

CREATE TABLE student_groups
(
    id           UUID    NOT NULL,
    project_id   UUID    NOT NULL,
    group_number INTEGER NOT NULL,
    CONSTRAINT pk_student_groups PRIMARY KEY (id)
);

CREATE TABLE students
(
    id       UUID NOT NULL,
    school_class_id UUID,
    CONSTRAINT pk_students PRIMARY KEY (id)
);

CREATE TABLE subject
(
    id          UUID NOT NULL,
    name        VARCHAR(100),
    description VARCHAR(255),
    CONSTRAINT pk_subject PRIMARY KEY (id)
);

CREATE TABLE teacher
(
    user_id UUID NOT NULL,
    CONSTRAINT pk_teacher PRIMARY KEY (user_id)
);

CREATE TABLE user_info
(
    user_id    UUID NOT NULL,
    first_name VARCHAR(100),
    last_name  VARCHAR(100),
    email      VARCHAR(255),
    CONSTRAINT pk_user_info PRIMARY KEY (user_id)
);

CREATE TABLE users
(
    id            UUID         NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    created_by    UUID,
    updated_by    UUID,
    username      VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    enabled       BOOLEAN      NOT NULL,
    disabled_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE project_subject
    ADD CONSTRAINT uc_9cae4b3d2e1b639441f482707 UNIQUE (project_id, subject_id);

ALTER TABLE user_info
    ADD CONSTRAINT uc_user_info_email UNIQUE (email);

ALTER TABLE class_projects
    ADD CONSTRAINT ux_class_projects_class_project UNIQUE (school_class_id, project_id);

ALTER TABLE grades
    ADD CONSTRAINT ux_grade_once_per_student_in_project_subject UNIQUE (project_subject_id, student_id);

ALTER TABLE group_members
    ADD CONSTRAINT ux_group_members_group_user UNIQUE (group_id, student_id);

ALTER TABLE student_groups
    ADD CONSTRAINT ux_student_groups_project_groupno UNIQUE (project_id, group_number);

ALTER TABLE users
    ADD CONSTRAINT ux_users_username UNIQUE (username);

ALTER TABLE admin
    ADD CONSTRAINT FK_ADMIN_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE audit_logs
    ADD CONSTRAINT FK_AUDIT_LOGS_ON_ACTOR FOREIGN KEY (actor_id) REFERENCES users (id);

CREATE INDEX ix_audit_logs_actor ON audit_logs (actor_id);

ALTER TABLE class_projects
    ADD CONSTRAINT FK_CLASS_PROJECTS_ON_CLASS FOREIGN KEY (school_class_id) REFERENCES school_class (id);

CREATE INDEX ix_class_projects_class ON class_projects (school_class_id);

ALTER TABLE class_projects
    ADD CONSTRAINT FK_CLASS_PROJECTS_ON_PROJECT FOREIGN KEY (project_id) REFERENCES project (id);

CREATE INDEX ix_class_projects_project ON class_projects (project_id);

ALTER TABLE grades
    ADD CONSTRAINT FK_GRADES_ON_PROJECT_SUBJECT FOREIGN KEY (project_subject_id) REFERENCES project_subject (id);

CREATE INDEX ix_grades_project_subject ON grades (project_subject_id);

ALTER TABLE grades
    ADD CONSTRAINT FK_GRADES_ON_STUDENT FOREIGN KEY (student_id) REFERENCES students (id);

CREATE INDEX ix_grades_student ON grades (student_id);

ALTER TABLE grades
    ADD CONSTRAINT FK_GRADES_ON_TEACHER FOREIGN KEY (teacher_id) REFERENCES teacher (user_id);

ALTER TABLE group_members
    ADD CONSTRAINT FK_GROUP_MEMBERS_ON_GROUP FOREIGN KEY (group_id) REFERENCES student_groups (id);

CREATE INDEX ix_group_members_group ON group_members (group_id);

ALTER TABLE group_members
    ADD CONSTRAINT FK_GROUP_MEMBERS_ON_STUDENT FOREIGN KEY (student_id) REFERENCES students (id);

CREATE INDEX ix_group_members_user ON group_members (student_id);

ALTER TABLE project
    ADD CONSTRAINT FK_PROJECT_ON_CLASS FOREIGN KEY (school_class_id) REFERENCES school_class (id);

ALTER TABLE project_subject
    ADD CONSTRAINT FK_PROJECT_SUBJECT_ON_PROJECT FOREIGN KEY (project_id) REFERENCES project (id);

ALTER TABLE project_subject
    ADD CONSTRAINT FK_PROJECT_SUBJECT_ON_SUBJECT FOREIGN KEY (subject_id) REFERENCES subject (id);

ALTER TABLE students
    ADD CONSTRAINT FK_STUDENTS_ON_CLASS FOREIGN KEY (school_class_id) REFERENCES school_class (id);

ALTER TABLE students
    ADD CONSTRAINT FK_STUDENTS_ON_ID FOREIGN KEY (id) REFERENCES users (id);

ALTER TABLE student_groups
    ADD CONSTRAINT FK_STUDENT_GROUPS_ON_PROJECT FOREIGN KEY (project_id) REFERENCES project (id);

ALTER TABLE teacher
    ADD CONSTRAINT FK_TEACHER_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE user_info
    ADD CONSTRAINT FK_USER_INFO_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);
