-- Ensure case-insensitive text support for email fields
CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE admin
(
    user_id UUID NOT NULL,
    CONSTRAINT pk_admin PRIMARY KEY (user_id)
);

CREATE TABLE assessment_answers
(
    id            UUID    NOT NULL,
    assessment_id UUID    NOT NULL,
    question_id   UUID    NOT NULL,
    score         INTEGER NOT NULL,
    CONSTRAINT pk_assessment_answers PRIMARY KEY (id)
);

CREATE TABLE assessments
(
    id                  UUID                        NOT NULL,
    questionnaire_id    UUID                        NOT NULL,
    project_id          UUID                        NOT NULL,
    type                VARCHAR(10)                 NOT NULL,
    assessor_student_id UUID                        NOT NULL,
    assessee_student_id UUID                        NOT NULL,
    submitted_at        TIMESTAMP WITHOUT TIME ZONE,
    created_at          TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at          TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_assessments PRIMARY KEY (id)
);

CREATE TABLE audit_logs
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    actor_id  UUID,
    action    VARCHAR(255)                            NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    details   VARCHAR(255),
    resource  VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_audit_logs PRIMARY KEY (id)
);

CREATE TABLE class_projects
(
    id              UUID    NOT NULL,
    school_class_id UUID    NOT NULL,
    project_id      UUID    NOT NULL,
    active          BOOLEAN NOT NULL,
    valid_from      TIMESTAMP WITHOUT TIME ZONE,
    valid_to        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_class_projects PRIMARY KEY (id)
);

CREATE TABLE class_subject_assignments
(
    id                        UUID                        NOT NULL,
    assignment_name           VARCHAR(255)                NOT NULL,
    school_class_id           UUID                        NOT NULL,
    term_id                   UUID                        NOT NULL,
    subject_id                UUID                        NOT NULL,
    teacher_id                UUID                        NOT NULL,
    final_grade_assignment_id UUID                        NOT NULL,
    weighting                 DECIMAL,
    created_at                TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at                TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_class_subject_assignments PRIMARY KEY (id)
);

CREATE TABLE class_terms
(
    id              UUID                        NOT NULL,
    school_class_id UUID                        NOT NULL,
    term_id         UUID                        NOT NULL,
    status          VARCHAR(10)                 NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_class_terms PRIMARY KEY (id)
);

CREATE TABLE final_grade_assignments
(
    id              UUID                        NOT NULL,
    assignment_name VARCHAR(255)                NOT NULL,
    school_class_id UUID                        NOT NULL,
    term_id         UUID                        NOT NULL,
    subject_id      UUID                        NOT NULL,
    teacher_id      UUID                        NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_final_grade_assignments PRIMARY KEY (id)
);

CREATE TABLE final_grades
(
    id                          UUID                        NOT NULL,
    final_grade_assignment_id   UUID                        NOT NULL,
    student_id                  UUID                        NOT NULL,
    grade_value                 DECIMAL(2, 1)               NOT NULL,
    created_at                  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at                  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    teacher_id                  UUID                        NOT NULL,
    CONSTRAINT pk_final_grades PRIMARY KEY (id)
);

CREATE TABLE grades
(
    id                          UUID                        NOT NULL,
    class_subject_assignment_id UUID                        NOT NULL,
    student_id                  UUID                        NOT NULL,
    grade_value                 DECIMAL(2, 1)               NOT NULL,
    created_at                  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at                  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    teacher_id                  UUID                        NOT NULL,
    CONSTRAINT pk_grades PRIMARY KEY (id)
);

CREATE TABLE group_members
(
    id         UUID                        NOT NULL,
    group_id   UUID                        NOT NULL,
    student_id UUID                        NOT NULL,
    role       VARCHAR(20),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_group_members PRIMARY KEY (id)
);

CREATE TABLE password_reset
(
    id           UUID                        NOT NULL,
    user_id      UUID                        NOT NULL,
    token_hash   BYTEA                       NOT NULL,
    token_salt   BYTEA                       NOT NULL,
    status       VARCHAR(255)                NOT NULL,
    expires_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    used_at      TIMESTAMP WITHOUT TIME ZONE,
    note         VARCHAR(255),
    public_token VARCHAR(255),
    CONSTRAINT pk_password_reset PRIMARY KEY (id)
);

CREATE TABLE project
(
    id              UUID                        NOT NULL,
    name            VARCHAR(255)                NOT NULL,
    description     VARCHAR(2000),
    school_class_id UUID                        NOT NULL,
    term_id         UUID                        NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    active          BOOLEAN                     NOT NULL,
    CONSTRAINT pk_project PRIMARY KEY (id)
);

CREATE TABLE project_groups
(
    id                     UUID                        NOT NULL,
    project_id             UUID                        NOT NULL,
    group_number           INTEGER                     NOT NULL,
    supervising_teacher_id UUID,
    created_at             TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at             TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_project_groups PRIMARY KEY (id)
);

CREATE TABLE questionnaires
(
    id                    UUID                        NOT NULL,
    project_id            UUID                        NOT NULL,
    status                VARCHAR(10)                 NOT NULL,
    created_by_teacher_id UUID                        NOT NULL,
    created_at            TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at            TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_questionnaires PRIMARY KEY (id)
);

CREATE TABLE questions
(
    id               UUID         NOT NULL,
    questionnaire_id UUID         NOT NULL,
    position         INTEGER      NOT NULL,
    text             VARCHAR(500) NOT NULL,
    active           BOOLEAN      NOT NULL,
    CONSTRAINT pk_questions PRIMARY KEY (id)
);

CREATE TABLE registration_invites
(
    id              UUID                        NOT NULL,
    email           CITEXT                      NOT NULL,
    role            VARCHAR(255)                NOT NULL,
    school_class_id UUID,
    public_token    VARCHAR(255),
    token_hash      BYTEA                       NOT NULL,
    token_salt      BYTEA                       NOT NULL,
    status          VARCHAR(255)                NOT NULL,
    expires_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    uses_count      INTEGER                     NOT NULL,
    max_uses        INTEGER                     NOT NULL,
    created_by      UUID                        NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    used_at         TIMESTAMP WITHOUT TIME ZONE,
    note            VARCHAR(255),
    CONSTRAINT pk_registration_invites PRIMARY KEY (id)
);

CREATE TABLE school_class
(
    id   UUID         NOT NULL,
    name VARCHAR(100) NOT NULL,
    CONSTRAINT pk_schoolclass PRIMARY KEY (id)
);

CREATE TABLE school_years
(
    id         UUID                        NOT NULL,
    name       VARCHAR(100)                NOT NULL,
    start_date date                        NOT NULL,
    end_date   date                        NOT NULL,
    status     VARCHAR(10)                 NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_school_years PRIMARY KEY (id)
);

CREATE TABLE students
(
    id              UUID NOT NULL,
    school_class_id UUID,
    CONSTRAINT pk_students PRIMARY KEY (id)
);

CREATE TABLE subject
(
    id          UUID NOT NULL,
    name        VARCHAR(100),
    description VARCHAR(255),
    CONSTRAINT pk_subject PRIMARY KEY (id)
);

CREATE TABLE teacher
(
    user_id UUID NOT NULL,
    CONSTRAINT pk_teacher PRIMARY KEY (user_id)
);

CREATE TABLE terms
(
    id              UUID                        NOT NULL,
    name            VARCHAR(255)                NOT NULL,
    status          VARCHAR(10)                 NOT NULL,
    sequence_number INTEGER,
    school_year_id  UUID                        NOT NULL,
    start_date      date                        NOT NULL,
    end_date        date                        NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_terms PRIMARY KEY (id)
);

CREATE TABLE user_info
(
    user_id    UUID NOT NULL,
    first_name VARCHAR(100),
    last_name  VARCHAR(100),
    email      VARCHAR(255),
    CONSTRAINT pk_user_info PRIMARY KEY (user_id)
);

CREATE TABLE users
(
    id            UUID         NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    created_by    UUID,
    updated_by    UUID,
    username      VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    enabled       BOOLEAN      NOT NULL,
    disabled_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE refresh_token
(
    id         UUID                        NOT NULL,
    user_id    UUID                        NOT NULL,
    token_hash BYTEA                       NOT NULL,
    token_salt BYTEA                       NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    revoked_at TIMESTAMP WITHOUT TIME ZONE,
    reused_at  TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_refresh_token PRIMARY KEY (id)
);

ALTER TABLE grades
    ADD CONSTRAINT grade_once_per_assignment_and_student UNIQUE (class_subject_assignment_id, student_id);

ALTER TABLE final_grades
    ADD CONSTRAINT final_grade_once_per_assignment_and_student UNIQUE (final_grade_assignment_id, student_id);

ALTER TABLE user_info
    ADD CONSTRAINT uc_user_info_email UNIQUE (email);

ALTER TABLE assessments
    ADD CONSTRAINT uk_assessment_peer UNIQUE (questionnaire_id, type, assessor_student_id, assessee_student_id);

ALTER TABLE assessments
    ADD CONSTRAINT uk_assessment_self UNIQUE (questionnaire_id, type, assessor_student_id);

ALTER TABLE class_subject_assignments
    ADD CONSTRAINT uk_class_subject_assignment UNIQUE (school_class_id, term_id, subject_id, teacher_id);

ALTER TABLE final_grade_assignments
    ADD CONSTRAINT uk_final_grade_assignment UNIQUE (school_class_id, term_id, subject_id, teacher_id);

ALTER TABLE class_terms
    ADD CONSTRAINT uk_class_term_class_term UNIQUE (school_class_id, term_id);

ALTER TABLE group_members
    ADD CONSTRAINT uk_group_student UNIQUE (group_id, student_id);

ALTER TABLE project_groups
    ADD CONSTRAINT uk_project_group_number UNIQUE (project_id, group_number);

ALTER TABLE questionnaires
    ADD CONSTRAINT uk_questionnaire_project UNIQUE (project_id);

ALTER TABLE class_projects
    ADD CONSTRAINT ux_class_projects_class_project UNIQUE (school_class_id, project_id);

ALTER TABLE users
    ADD CONSTRAINT ux_users_username UNIQUE (username);

ALTER TABLE admin
    ADD CONSTRAINT FK_ADMIN_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE assessments
    ADD CONSTRAINT FK_ASSESSMENTS_ON_QUESTIONNAIRE FOREIGN KEY (questionnaire_id) REFERENCES questionnaires (id);

ALTER TABLE assessment_answers
    ADD CONSTRAINT FK_ASSESSMENT_ANSWERS_ON_ASSESSMENT FOREIGN KEY (assessment_id) REFERENCES assessments (id);

ALTER TABLE assessment_answers
    ADD CONSTRAINT FK_ASSESSMENT_ANSWERS_ON_QUESTION FOREIGN KEY (question_id) REFERENCES questions (id);

ALTER TABLE audit_logs
    ADD CONSTRAINT FK_AUDIT_LOGS_ON_ACTOR FOREIGN KEY (actor_id) REFERENCES users (id);

CREATE INDEX ix_audit_logs_actor ON audit_logs (actor_id);

ALTER TABLE class_projects
    ADD CONSTRAINT FK_CLASS_PROJECTS_ON_PROJECT FOREIGN KEY (project_id) REFERENCES project (id);

CREATE INDEX ix_class_projects_project ON class_projects (project_id);

ALTER TABLE class_projects
    ADD CONSTRAINT FK_CLASS_PROJECTS_ON_SCHOOL_CLASS FOREIGN KEY (school_class_id) REFERENCES school_class (id);

CREATE INDEX ix_class_projects_class ON class_projects (school_class_id);

ALTER TABLE class_subject_assignments
    ADD CONSTRAINT FK_CLASS_SUBJECT_ASSIGNMENTS_ON_FINAL_GRADE_ASSIGNMENT FOREIGN KEY (final_grade_assignment_id) REFERENCES final_grade_assignments (id);

ALTER TABLE class_subject_assignments
    ADD CONSTRAINT FK_CLASS_SUBJECT_ASSIGNMENTS_ON_SCHOOL_CLASS FOREIGN KEY (school_class_id) REFERENCES school_class (id);

ALTER TABLE class_subject_assignments
    ADD CONSTRAINT FK_CLASS_SUBJECT_ASSIGNMENTS_ON_SUBJECT FOREIGN KEY (subject_id) REFERENCES subject (id);

ALTER TABLE class_subject_assignments
    ADD CONSTRAINT FK_CLASS_SUBJECT_ASSIGNMENTS_ON_TEACHER FOREIGN KEY (teacher_id) REFERENCES teacher (user_id);

ALTER TABLE class_subject_assignments
    ADD CONSTRAINT FK_CLASS_SUBJECT_ASSIGNMENTS_ON_TERM FOREIGN KEY (term_id) REFERENCES terms (id);

ALTER TABLE class_terms
    ADD CONSTRAINT FK_CLASS_TERMS_ON_SCHOOL_CLASS FOREIGN KEY (school_class_id) REFERENCES school_class (id);

ALTER TABLE class_terms
    ADD CONSTRAINT FK_CLASS_TERMS_ON_TERM FOREIGN KEY (term_id) REFERENCES terms (id);

ALTER TABLE final_grade_assignments
    ADD CONSTRAINT FK_FINAL_GRADE_ASSIGNMENTS_ON_SCHOOL_CLASS FOREIGN KEY (school_class_id) REFERENCES school_class (id);

ALTER TABLE final_grade_assignments
    ADD CONSTRAINT FK_FINAL_GRADE_ASSIGNMENTS_ON_SUBJECT FOREIGN KEY (subject_id) REFERENCES subject (id);

ALTER TABLE final_grade_assignments
    ADD CONSTRAINT FK_FINAL_GRADE_ASSIGNMENTS_ON_TEACHER FOREIGN KEY (teacher_id) REFERENCES teacher (user_id);

ALTER TABLE final_grade_assignments
    ADD CONSTRAINT FK_FINAL_GRADE_ASSIGNMENTS_ON_TERM FOREIGN KEY (term_id) REFERENCES terms (id);

ALTER TABLE grades
    ADD CONSTRAINT FK_GRADES_ON_CLASS_SUBJECT_ASSIGNMENT FOREIGN KEY (class_subject_assignment_id) REFERENCES class_subject_assignments (id);

ALTER TABLE grades
    ADD CONSTRAINT FK_GRADES_ON_STUDENT FOREIGN KEY (student_id) REFERENCES students (id);

ALTER TABLE grades
    ADD CONSTRAINT FK_GRADES_ON_TEACHER FOREIGN KEY (teacher_id) REFERENCES teacher (user_id);

ALTER TABLE final_grades
    ADD CONSTRAINT FK_FINAL_GRADES_ON_FINAL_GRADE_ASSIGNMENT FOREIGN KEY (final_grade_assignment_id) REFERENCES final_grade_assignments (id);

ALTER TABLE final_grades
    ADD CONSTRAINT FK_FINAL_GRADES_ON_STUDENT FOREIGN KEY (student_id) REFERENCES students (id);

ALTER TABLE final_grades
    ADD CONSTRAINT FK_FINAL_GRADES_ON_TEACHER FOREIGN KEY (teacher_id) REFERENCES teacher (user_id);

ALTER TABLE group_members
    ADD CONSTRAINT FK_GROUP_MEMBERS_ON_GROUP FOREIGN KEY (group_id) REFERENCES project_groups (id);

ALTER TABLE group_members
    ADD CONSTRAINT FK_GROUP_MEMBERS_ON_STUDENT FOREIGN KEY (student_id) REFERENCES students (id);

ALTER TABLE project_groups
    ADD CONSTRAINT FK_PROJECT_GROUPS_ON_PROJECT FOREIGN KEY (project_id) REFERENCES project (id);

ALTER TABLE project_groups
    ADD CONSTRAINT FK_PROJECT_GROUPS_ON_SUPERVISING_TEACHER FOREIGN KEY (supervising_teacher_id) REFERENCES teacher (user_id);

ALTER TABLE project
    ADD CONSTRAINT FK_PROJECT_ON_SCHOOL_CLASS FOREIGN KEY (school_class_id) REFERENCES school_class (id);

ALTER TABLE project
    ADD CONSTRAINT FK_PROJECT_ON_TERM FOREIGN KEY (term_id) REFERENCES terms (id);

ALTER TABLE questions
    ADD CONSTRAINT FK_QUESTIONS_ON_QUESTIONNAIRE FOREIGN KEY (questionnaire_id) REFERENCES questionnaires (id);

ALTER TABLE refresh_token
    ADD CONSTRAINT FK_REFRESH_TOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE students
    ADD CONSTRAINT FK_STUDENTS_ON_ID FOREIGN KEY (id) REFERENCES users (id);

ALTER TABLE students
    ADD CONSTRAINT FK_STUDENTS_ON_SCHOOL_CLASS FOREIGN KEY (school_class_id) REFERENCES school_class (id);

ALTER TABLE teacher
    ADD CONSTRAINT FK_TEACHER_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE terms
    ADD CONSTRAINT FK_TERMS_ON_SCHOOL_YEAR FOREIGN KEY (school_year_id) REFERENCES school_years (id);

ALTER TABLE user_info
    ADD CONSTRAINT FK_USER_INFO_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);
